project_id = "pczjwunwitxnhhtxltph"

[functions.omniway]
verify_jwt = false

[functions.storepay]
verify_jwt = false

[functions.migrate-legacy]
verify_jwt = false

[functions.import-users-xml]
verify_jwt = false