project_id = "pczjwunwitxnhhtxltph"

[functions.translate-titles]
verify_jwt = false

[functions.translate-search]
verify_jwt = false

[functions.omniway]
verify_jwt = false

[functions.storepay]
verify_jwt = false

[functions.migrate-legacy]
verify_jwt = false

[functions.import-users-xml]
verify_jwt = false

[functions.amazon-api]
verify_jwt = false